#!/usr/bin/env python3
"""
Generate splash_bitmap.h — a C header containing the 4-bit-packed
framebuffer the splash binary paints onto the SH1122.

Usage:
    ./gen-bitmap.py splash_bitmap.h

Renders "KODE NAS" centred on a 256x64 canvas with "loading…"
underneath, packs the 8-bit greyscale image into the SH1122's
nibble-per-pixel format (high nibble = left pixel, low nibble =
right pixel), and writes the result as a static C array.

Re-run any time the splash text or layout changes. The Makefile
calls this for you during `make`.
"""

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

WIDTH, HEIGHT = 256, 64
TITLE = "KODE NAS"
SUBTITLE = "loading…"

# DejaVu is installed by default on Debian-derived hosts (and is in
# the build.sh pre-flight check). Fall back to PIL's built-in font
# if it's missing so the build still produces *something*.
FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    "/Library/Fonts/DejaVu Sans Bold.ttf",
]


def _load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for path in FONT_CANDIDATES:
        if Path(path).is_file():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def _draw_centred(draw: ImageDraw.ImageDraw, text: str,
                  font, baseline_y: int) -> None:
    bbox = draw.textbbox((0, 0), text, font=font)
    x = (WIDTH - (bbox[2] - bbox[0])) // 2 - bbox[0]
    draw.text((x, baseline_y), text, fill=255, font=font)


def render() -> bytes:
    img = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(img)
    _draw_centred(draw, TITLE,    _load_font(28), 0)
    _draw_centred(draw, SUBTITLE, _load_font(16), 38)
    return img.tobytes()


def pack_4bit(grey: bytes) -> bytes:
    """SH1122 packs 2 horizontal pixels per byte (hi nibble = left)."""
    out = bytearray(WIDTH // 2 * HEIGHT)
    for i in range(0, len(grey), 2):
        out[i >> 1] = (grey[i] & 0xF0) | (grey[i + 1] >> 4)
    return bytes(out)


def write_header(path: Path, fb: bytes) -> None:
    lines = [
        "/* Auto-generated by gen-bitmap.py — do not edit by hand. */",
        "#ifndef KODE_SPLASH_BITMAP_H",
        "#define KODE_SPLASH_BITMAP_H",
        "",
        "#include <stdint.h>",
        "",
        f"static const uint8_t splash_framebuffer[{len(fb)}] = {{",
    ]
    for i in range(0, len(fb), 16):
        row = ", ".join(f"0x{b:02x}" for b in fb[i:i + 16])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* KODE_SPLASH_BITMAP_H */")
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    out_path = Path(sys.argv[1])
    fb = pack_4bit(render())
    write_header(out_path, fb)
    print(f"wrote {out_path} ({len(fb)} bytes of framebuffer)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
